/* protocol.h */
/* (C) SPRUE Ltd 2014 */

/** @file
 *
 * SPRUE radio module protocol.
 *
 * @author Richard Watts <rrw@kynesim.co.uk>
 * @date   2014-08-13
 */

#ifndef SPRUERM_PROTOCOL_H_INCLUDED
#define SPRUERM_PROTOCOL_H_INCLUDED

/* Sprue radio module packet requests are characterised by
 *  a command byte and a length, packed as LSB and byte 1
 *  of an unsigned int.
 *
 *  byte 2 tells you whether this is from RM to SD (0)
 *  or SD to RM (1)
 */
#define SPRUERM_PKT(cmd,bytes,from_sd)  \
    ((cmd) | ((bytes) << 8) |           \
     ((SPRUERM_##from_sd) << 16))
    
#define SPRUERM_CMD_OF(x)  ((x) & 0xff)
#define SPRUERM_BYTES_OF(x) (((x)>>8) & 0xff)
#define SPRUERM_TYPE_OF(x) (((x)>>16)& 0xff)

#define SPRUERM_CMD(x) ((SPRUERM_##x)&0xff)

#define SPRUERM_COMMAND (2)
#define SPRUERM_RESPONSE (1)
#define SPRUERM_REPEATING (3)
#define SPRUERM_COMMAND_FORWARDED (4|2)
#define SPRUERM_RESPONSE_FORWARDED (4|1)

#define SPRUERM_FORWARDED_FLAG (4<<16)

#define SPRUERM_ACK  SPRUERM_PKT(0x46, 0x01, RESPONSE)
#define SPRUERM_NACK SPRUERM_PKT(0x47, 0x01, RESPONSE)
#define SPRUERM_STATUS_REQ SPRUERM_PKT(0x41, 0x01, COMMAND)
#define SPRUERM_ALARM_IDENT SPRUERM_PKT(0x91, 10, RESPONSE)

/* S4.3.1: Calibration */
#define SPRUERM_UNCALIBRATED SPRUERM_PKT(0x01, 8, REPEATING)
#define SPRUERM_DO_TEMPERATURE_CAL SPRUERM_PKT(0x10, 2, COMMAND)
#define SPRUERM_TEMP_CAL_PASS SPRUERM_PKT(0x11, 3, RESPONSE)
#define SPRUERM_TEMP_CAL_FAIL SPRUERM_PKT(0x12, 3, RESPONSE)
#define SPRUERM_DO_CAL_ADJUST_SELECT SPRUERM_PKT(0x15, 2, COMMAND)
#define SPRUERM_DO_CAL_ADJUST_UP  SPRUERM_PKT(0x16, 2, COMMAND)
#define SPRUERM_DO_CAL_ADJUST_DOWN SPRUERM_PKT(0x17, 2, COMMAND)
#define SPRUERM_CAL_ADJUST_PASS   SPRUERM_PKT(0x18, 3, RESPONSE)
#define SPRUERM_CAL_ADJUST_FAIL   SPRUERM_PKT(0x19, 3, RESPONSE)
#define SPRUERM_DO_CAL_1          SPRUERM_PKT(0x20, 1, COMMAND)
#define SPRUERM_CAL_1_PROC        SPRUERM_PKT(0x21, 8, RESPONSE)
#define SPRUERM_CAL_1_PASS        SPRUERM_PKT(0x22, 3, RESPONSE)
#define SPRUERM_CAL_1_FAIL        SPRUERM_PKT(0x23, 3, RESPONSE)
#define SPRUERM_DO_CAL_2          SPRUERM_PKT(0x30, 1, COMMAND)
#define SPRUERM_CAL_2_PROC        SPRUERM_PKT(0x31, 8, RESPONSE)
#define SPRUERM_CAL_2_PASS        SPRUERM_PKT(0x32, 3, RESPONSE)
#define SPRUERM_CAL_2_FAIL        SPRUERM_PKT(0x33, 3, RESPONSE)
#define SPRUERM_CAL_FINALISE      SPRUERM_PKT(0x3F, 3, COMMAND)
#define SPRUERM_CAL_RESET         SPRUERM_PKT(0x0F, 1, COMMAND)

/* Local Diagnostics, S4.3.2 */
#define SPRUERM_SEND_OPP_DATA    SPRUERM_PKT(0x81, 1, COMMAND)
#define SPRUERM_OPP_DATA         SPRUERM_PKT(0x94, 9, RESPONSE)
#define SPRUERM_SEND_EEPROM      SPRUERM_PKT(0x82, 1, COMMAND)
#define SPRUERM_EEPROM_DATA      SPRUERM_PKT(0x92, 18, RESPONSE)
#define SPRUERM_SEND_LIVEDATA    SPRUERM_PKT(0x83, 1, COMMAND)
#define SPRUERM_STOP_LIVEDATA    SPRUERM_PKT(0x84, 1, COMMAND)
#define SPRUERM_LIVEDATA         SPRUERM_PKT(0x93, 26, RESPONSE)
#define SPRUERM_DO_OPERATION_TEST SPRUERM_PKT(0xA0, 2, COMMAND)
#define SPRUERM_DO_OPERATION_STOP SPRUERM_PKT(0xA1, 1, COMMAND)
#define SPRUERM_OPERATION_TEST_RESULT SPRUERM_PKT(0xA2, 9, RESPONSE)
#define SPRUERM_RESET_HOURS       SPRUERM_PKT(0x85, 1, COMMAND)
#define SPRUERM_RESET_ACTIVATIONS  SPRUERM_PKT(0x86, 1, COMMAND)
#define SPRUERM_CLEAR_ALARMS      SPRUERM_PKT(0x87, 1, COMMAND)
#define SPRUERM_CLEAR_FAULTS      SPRUERM_PKT(0x88, 1, COMMAND)
#define SPRUERM_RESET_DEVICE      SPRUERM_PKT(0x89, 1, COMMAND)

/* S4.4: WiSafeII implemented messages */

#define SPRUERM_ALARM             SPRUERM_PKT(0x50, 6, COMMAND_FORWARDED)
#define SPRUERM_ALARM_STOP        SPRUERM_PKT(0x51, 5, COMMAND_FORWARDED)
#define SPRUERM_HUSH              SPRUERM_PKT(0x60, 5, COMMAND_FORWARDED)
#define SPRUERM_LOCATE            SPRUERM_PKT(0x61, 6, COMMAND_FORWARDED)
#define SPRUERM_NOTIFY_SID        SPRUERM_PKT(0x62, 6, COMMAND_FORWARDED)
#define SPRUERM_NOTIFY_DEV_ID     SPRUERM_PKT(0x63, 6, COMMAND_FORWARDED)
#define SPRUERM_DEVICE_TESTED     SPRUERM_PKT(0x70, 8, COMMAND_FORWARDED)
#define SPRUERM_FAULT             SPRUERM_PKT(0x71, 7, RESPONSE_FORWARDED)
#define SPRUERM_REQ_FAULT_DETAILS SPRUERM_PKT(0x72, 7, COMMAND_FORWARDED)
#define SPRUERM_FAULT_DETAILS     SPRUERM_PKT(0x73, 8, RESPONSE_FORWARDED)
#define SPRUERM_DO_DIAGNOSTIC     SPRUERM_PKT(0xC1, 8, COMMAND_FORWARDED)
#define SPRUERM_DIAGNOSTIC_RESULT SPRUERM_PKT(0xC2, 8, RESPONSE_FORWARDED)
#define SPRUERM_DO_EXTDIG_ID      SPRUERM_PKT(0xC3, 4, COMMAND_FORWARDED)
#define SPRUERM_DO_EXTDIG_ID_RESULT SPRUERM_PKT(0xC4, 7, RESPONSE_FORWARDED)
#define SPRUERM_DO_EXTDIG_EEPROM   SPRUERM_PKT(0xC5, 7, COMMAND_FORWARDED)
#define SPRUERM_EXTDIG_EEPROM_RESULT SPRUERM_PKT(0xC6, 9, RESPONSE_FORWARDED)
#define SPRUERM_DO_EXTDIG_DATASLOT SPRUERM_PKT(0xC7,7, COMMAND_FORWARDED)
#define SPRUERM_EXTDIG_DATASLOT_RESULT SPRUERM_PKT(0xC8, 9, RESPONSE_FORWARDED)

/* S4.5 RM Messages */
#define SPRUERM_RM_DIAGNOSTIC_REQUEST SPRUERM_PKT(0xD1, 1, COMMAND)
#define SPRUERM_RM_DIAGNOSTIC_RESULT  SPRUERM_PKT(0xD2, 13, RESPONSE)
#define SPRUERM_RM_EXTDIAG_REQUEST SPRUERM_PKT(0xD3, 0xFF, COMMAND)
#define SPRUERM_RM_EXTDIAG_RESPONSE SPRUERM_PKT(0xD4, 0xFF, RESPONSE)
#define SPRUERM_RM_SD_FAULT         SPRUERM_PKT(0xD5, 7, RESPONSE)
#define SPRUERM_RM_CLEAR            SPRUERM_PKT(0xE2, 1, COMMAND)
#define SPRUERM_RM_RESET            SPRUERM_PKT(0xE5, 1, RESPONSE)
#define SPRUERM_RM_ID_REQUEST       SPRUERM_PKT(0xE6, 1, COMMAND)
#define SPRUERM_RM_ID_RESPONCE      SPRUERM_PKT(0xE7, 7, RESPONSE)
#define SPRUERM_RM_PRODUCTION_TEST_CMD SPRUERM_PKT(0xE8, 2, COMMAND)
#define SPRUERM_RM_PRODUCTION_TEST_RESPONCE SPRUERM_PKT(0xE9, 0xFF, RESPONSE)


#endif
